#
# $Id$

# Author(s):  Anton Deguet
# Created on: 2011-01-20
#
# (C) Copyright 2011 Johns Hopkins University (JHU), All Rights
# Reserved.
#

# this file is automatically generated by CMake from
# sawOpenIGTLinkConfig.cmake.in

set (sawOpenIGTLink-dev_INCLUDE_DIR "/home/xli4217/Desktop/usoverlay/src/usoverlay_src/include")
set (sawOpenIGTLink-dev_LIBRARY_DIR ";/usr/local/lib/igtl")
set (sawOpenIGTLink-dev_LIBRARIES   "sawOpenIGTLink-dev;OpenIGTLink")
